AppEmpresas/AppEmpresas/Models/Empresa.cs
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;

namespace AppEmpresas.Models
{
    public class Empresa
    {
        public Guid Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string UserId { get; set; }

    }
}

AppEmpresas/AppEmpresas/Models/EmpresaViewModel.cs
namespace AppEmpresas.Models
{
    public class EmpresaViewModel
    {
        public Empresa[] Empresas { get; set; }
    }
}

AppEmpresas/AppEmpresas/Models/ErrorViewModel.cs
using System;

namespace AppEmpresas.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AppEmpresas/AppEmpresas/Models/ManageUsersViewModel.cs
using Microsoft.AspNetCore.Identity;

namespace AppEmpresas.Models
{
  public class ManageUsersViewModel
  {
    public IdentityUser[] Administrators { get; set; }
    public IdentityUser[] Everyone { get; set; }
  }
}

AppEmpresas/AppEmpresas/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AppEmpresas.Models;

namespace AppEmpresas.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AppEmpresas/AppEmpresas/Controllers/ManageUsersController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using AppEmpresas.Models;

namespace AppEmpresas.Controllers
{
  [Authorize(Roles = "Administrator")]
  public class ManageUsersController : Controller
  {
    private readonly UserManager<IdentityUser> _userManager;

    public ManageUsersController(UserManager<IdentityUser> userManager)
    {
      _userManager = userManager;
    }
    public async Task<IActionResult> Index()
    {
      var admins = (await _userManager
      .GetUsersInRoleAsync("Administrator"))
      .ToArray();
      var everyone = await _userManager.Users
      .ToArrayAsync();
      var model = new ManageUsersViewModel
      {
        Administrators = admins,
        Everyone = everyone
      };
      return View(model);
    }
  }
}

AppEmpresas/AppEmpresas/Views/Empresas/AddEmpresaPartial.cshtml
@model Empresa
<form action="/Empresa/AddEmpresa" method="POST">
    <label asp-for="Name">Incluir nova empresa:</label>
    <input asp-for="Name">
    <button type="submit">Enviar</button>
</form>

AppEmpresas/AppEmpresas/Views/Empresas/Index.cshtml
@model EmpresaViewModel
<div class="panel-footer add-item-form">
    @await Html.PartialAsync("AddItemPartial", new Empresa())
</div>

AppEmpresas/AppEmpresas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">ioasys</h1>
    <p>Teste inicial de .NET : Mauro Damasceno.</p>
</div>
<div class="panel-footer add-item-form">
    @await Html.PartialAsync("AddEmpresaPartial", new Empresa())
</div>

AppEmpresas/AppEmpresas/Views/ManageUsers/Index.cshtml
@model ManageUsersViewModel

@{
  ViewData["Title"] = "Manage users";
}

<h2>@ViewData["Title"]</h2>

<h3>Administrators</h3>

<table class="table">
  <thead>
    <tr>
      <td>Id</td>
      <td>Email</td>
    </tr>
  </thead>

@foreach (var user in Model.Administrators)
{
    <tr>
      <td>@user.Id</td>
      <td>@user.Email</td>
    </tr>
}

</table>

<h3>Everyone</h3>

<table class="table">
  <thead>
    <tr>
      <td>Id</td>
      <td>Email</td>
    </tr>
  </thead>

  @foreach (var user in Model.Everyone)
  {
    <tr>
      <td>@user.Id</td>
      <td>@user.Email</td>
    </tr>
  }
  
</table>

AppEmpresas/AppEmpresas/Views/Shared/_AdminActionsPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using AppEmpresas.Models

@inject SignInManager<IdentityUser> signInManager
@inject UserManager<IdentityUser> userManager

@if (signInManager.IsSignedIn(User))
{
  var currentUser = await userManager.GetUserAsync(User);
  
  var isAdmin = currentUser != null
    && await userManager.IsInRoleAsync(
      currentUser,
      Constants.AdministratorRole);

  if (isAdmin)
  {
    <ul class="nav navbar-nav navbar-right">
      <li>
        <a asp-controller="ManageUsers"
          asp-action="Index">
          Manage Users
        </a>
      </li>
    </ul>
  }
}

AppEmpresas/AppEmpresas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppEmpresas</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppEmpresas</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                            <partial name="_LoginPartial" />
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Empresas" asp-action="Index">Empresas :)</a>
                                </li>
                            </ul>
                        </div>
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                    @await Html.PartialAsync("_AdminActionsPartial")
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - AppEmpresas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>